"""change instructions to _instructions

Revision ID: 323315162038
Revises: 9526ec328b1a
Create Date: 2025-06-24 13:46:46.553850

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '323315162038'
down_revision = '9526ec328b1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_instructions', sa.String(length=50), nullable=False))
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('_instructions')

    # ### end Alembic commands ###
