"""change column name _instructions to instruction

Revision ID: c90fd4f4213c
Revises: 323315162038
Create Date: 2025-06-25 20:00:32.245992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c90fd4f4213c'
down_revision = '323315162038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('instructions', sa.String(), nullable=False))
        batch_op.drop_column('_instructions')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_instructions', sa.VARCHAR(length=50), nullable=False))
        batch_op.drop_column('instructions')

    # ### end Alembic commands ###
